language: ruby

branches:
  only:
    - master
    - travis

rvm:
  - 2.1
  - 2.2
  - 2.3
  - jruby
  - rbx

env:
  - HANDLER=nokogiri
  - HANDLER=ox

matrix:
  allow_failures:
    - rvm: jruby
  exclude:
    - rvm: jruby
      env: HANDLER=ox

before_install:
  - gem update bundler
