language: ruby

cache: bundler

rvm:
  - 2.1
  - 2.2
  - 2.3
  - jruby-9
  - rbx

env:
  - HANDLER=nokogiri
  - HANDLER=ox

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-9
  exclude:
    - rvm: jruby-9
      env: HANDLER=ox

before_install:
  - gem update bundler

script:
  - bundle exec rake
